// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.Title}

  [![GitHub license](https://img.shields.io/badge/license-MIT-blue.svg)](https://github.com/${data.Username}/${data.Title})

  # Description

  ${data.Description}

  # Table of Contents

  * [Installation](#installation)

  * [Usage](#usage)

  * [License](#license)
  
  * [Contributing](#contributing)

  * [Instructions](#instructions)

  * [Questions](#questions)

  # Installation

  The following is necessary dependencies and must be installed to run the application properly: ${data.Installation}

  # Usage 

  This application is used for ${data.Usage}

  # License 

  This project is license under the ${data.license} license.

  # Contribution

  Contributors: ${data.Contributor}

  # Instructions

  To run this App, you need to follow these instructions: ${data.Instructions}

  # Questions

  If you have any questions about the repo, open an issue or contact [${data.Username}](https://github.com/${data.Username}) Email at ${data.Email}.

  This README was generated by [README-Generator](https://https://github.com/DeanMahaffey/README-Generator)

`;
}

module.exports = generateMarkdown;
